name = "ranguli"
license = "MIT"
licenselink = "https://github.com/ranguli/blank/blob/master/LICENSE"
description = "Starter Hugo theme for developers."
homepage = "https://github.com/ranguli/blank/"
tags = ["blog", "minimal", "dark", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "ranguli"
  homepage = "https://github.com/ranguli"
